ISPGBSS-645 style updates on control page
CMSgov/ato-blueprint pull request #9
Opened 2021-11-30 20:55 UTC by amyd11

https://jiraent.cms.gov/browse/ISPGBSS-645

### Changes
- misc style updates for spacing and alignment
- updated title text and added subtitle text
- removed columns from table
- added security sensitivity to the controls_selected function in the view
- updated right hand menu button text to match mockup
- updated string mapping for statuses on controls

### Testing
- visit the controls page for a project and verify changes align with [Figma mockup](https://www.figma.com/file/9a26GjOwssW76cTr01hfXL/Guidelines-%26-Wireframes?node-id=37%3A204) 

_Note: Page margins and Menu will be updated in separate stories_

2021-12-02 13:11 UTC, TMCamp requested changes

2021-12-02 13:11 UTC, TMCamp commented on controls/views.py
> +
Let's remove this newline character. PEP8 has this to say about blank lines: `Use blank lines in functions, sparingly, to indicate logical sections.` (https://www.python.org/dev/peps/pep-0008/#blank-lines)

2021-12-02 13:11 UTC, TMCamp commented on templates/systems/controls_selected.html
> +          To change the control baseline for this system, use the
I think that we should remove this line for now since I went through the process of changing my impact level and after answering a dozen questions and telling it to change my impact level, nothing happened.

2021-12-06 13:58 UTC, amyd11 commented on templates/systems/controls_selected.html
> +          To change the control baseline for this system, use the
Good point. If/when the updating an impact level gets implemented then we can add this text back in.

2021-12-06 13:59 UTC, amyd11 commented on controls/views.py
> +
Thanks for this- It's always helpful to know what the conventions are!

2021-12-06 14:05 UTC, TMCamp approved these changes

2021-12-06 14:10 UTC, merged